---

- hosts: "DATAMASTER:DATASLAVES:SERVICES"
  # concurrency is controlled via ansible.cfg:forks=1!
  connection: local
  # no need to gather facts of stopped machines
  gather_facts: no
  tasks:
    - name: "Start this machine"
      local_action: command cloudiosays-startvm "{{ inventory_hostname }}"
  
- hosts: "DELAYED_15"
  connection: local
  # concurrency is controlled via ansible.cfg:forks=1!
  tasks:
    - name: "timeout"
      pause: seconds=900
    - name: "Start this machine"
      local_action: command cloudiosays-startvm "{{ inventory_hostname }}"
